config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == 'haelo' && password == 'haelo'
end if Rails.env.production?

Wei::Application.routes.draw do

  get '/admin' => 'admin/logins#index'

  get '/wechat/auth/:storage_name' => 'wechats#auth'

  resource :wechat, only: [:show, :create] do
    get :wx_config, on: :collection
  end
  mount Sidekiq::Web => '/admin/sidekiq'

  resources :pages, only: [:show], param: :code
  resources :storages, param: :key, only: [:show, :create] do
    post :append, on: :collection
  end
  resources :types, only: [:show], param: :code
  resources :orders, onlt: [:show, :create]

  resources :payments, only: [:create] do
    post :wx_notify, on: :collection
  end

  resource :delivery_infos, only: [:create]
end

app/views/admin/pages/_page.html.erb
<div class="panel panel-default" style="overflow: hidden">
  <div class="panel-heading">
    <h3 class="panel-title">文章</h3>
  </div>
  <div class="panel-body">
    <label>
      标题：<input class="form-control" name="page[title]" value="<%= @page.title %>">
    </label>
    <label style="margin-left: 100px;">
      标识：<input class="form-control" name="page[code]" value="<%= @page.code %>">
    </label>
    <label style="margin-left: 100px;">
      类型：
      <select name="page[page_type]" class="form-control">
          <option value="raw" <%= 'selected' if @page.page_type == 'raw' %>>全文渲染</option>
          <option value="article" <%= 'selected' if @page.page_type == 'article' %>>文章</option>
      </select>
    </label>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">HTML</h3>
  </div>
  <div class="panel-body">
    <textarea name="page[content]" id="html-template" title="模版"><%= @page.content %></textarea>
  </div>

</div>
<button type="submit" class="btn btn-primary">提交</button>

app/views/admin/pages/account_pages.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>名称</th>
    <th>代码</th>
    <th>类型</th>
    <th>所属账号</th>
    <th>创建时间</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.id %></td>
      <td><%= page.title %></td>
      <td><%= page.code %></td>
      <td><%= page.page_type %></td>
      <td><%= page.public_account.name %></td>
      <td><%= page.created_at %></td>
      <td>
        <%= link_to "预览", page_path(code: page.code), class: "btn btn-success", target: '_blank' %>
        <%= link_to "编辑", edit_admin_page_path(page, public_account_id: page.public_account.id), class: "btn btn-primary" %>
        <%= link_to "删除", admin_page_path(page, public_account_id: page.public_account.id), method: :delete, data: { confirm: '确认删除吗？' }, class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/pages/edit.html.erb
<form class="form-group" method="post" action="<%= admin_page_path(@page, public_account_id: @account.id) %>">
  <input type="hidden" name="_method" value="put" />
  <%= render 'page' %>
</form>
<script>
    const tabSizeeditor = CodeMirror.fromTextArea(document.getElementById("html-template"), {
        lineNumbers: false,
        mode: "text/html",
        extraKeys: {
            "Esc": function(cm) {
                cm.setOption("fullScreen", !cm.getOption("fullScreen"));
            },
            "Tab": function(cm){
                cm.replaceSelection("  " , "end");
            }
        },
        tabSize: 2,
        indentWithTabs: false
    });
    editor.setSize('auto','800px');
</script>

app/views/admin/pages/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>公众号名称</th>
    <th>公众号账户</th>
    <th>页面数量</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.id %></td>
      <td><%= account.name %></td>
      <td><%= account.account %></td>
      <td><%= account.pages.count %></td>
      <td>
        <%= link_to "详情", account_pages_admin_pages_path(public_account_id: account.id), class: "btn btn-primary" %>
        <%= link_to "新建", new_admin_page_path(public_account_id: account.id), class: "btn btn-success" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/pages/new.html.erb
<form class="form-group" method="post" action="<%= admin_pages_path(public_account_id: @account.id) %>">
  <%= render 'page' %>
</form>
<script>
    const editor = CodeMirror.fromTextArea(document.getElementById("html-template"), {
        lineNumbers: false,
        mode: "text/html",
        extraKeys: {
            "Esc": function(cm) {
                cm.setOption("fullScreen", !cm.getOption("fullScreen"));
            },
            "Tab": function(cm){
                cm.replaceSelection("  " , "end");
            }
        },
        tabSize: 2,
        indentWithTabs: false
    });
    editor.setSize('auto','800px');
</script>